#!/usr/bin/env python3
import socket 
import datetime 
 

server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM) 
 

server_socket.bind(("0.0.0.0", 1303)) 
 

server_socket.listen(5) 
 
try: 
    while True: 
        client_socket, client_address = server_socket.accept() 
        print("Connecting from ", client_address) 
  
        current_time = datetime.datetime.now().strftime("%d.%m.%Y %H:%M") 
 
        client_socket.send(current_time.encode()) 
  
        client_socket.close() 
except KeyboardInterrupt: 
    print("Server is stopped") 
finally: 
    server_socket.close()
